// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"aesir/src"
	"aesir/src/channels"
	"aesir/src/common"
	"aesir/src/common/database"
	"aesir/src/crons"
	"aesir/src/slackbot"
	"aesir/src/users"
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
)

// Injectors from wire.go:

func New() (*fiber.App, error) {
	config := common.NewConfig()
	db := database.NewDB(config)
	userRepository := users.NewUserRepository(db)
	userService := users.NewUserService(userRepository)
	userHandler := users.NewUserHandler(userService)
	channelRepository := channels.NewChannelRepository(db)
	channelService := channels.NewChannelService(channelRepository)
	channelHandler := channels.NewChannelHandler(channelService)
	slackService := slackbot.NewSlackService(config)
	slackHandler := slackbot.NewSlackHandler(slackService)
	cronService := crons.NewCronService(config, slackService, userService)
	app := src.NewApp(config, db, userHandler, channelHandler, slackHandler, cronService)
	return app, nil
}

// wire.go:

var WireSet = wire.NewSet(src.AppSet)
